name: Feature request
description: Suggest an idea for this project
title: '[FEATURE]: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: Suggest a new feature or improvement for Numbott.
  - type: textarea
    id: feature
    attributes:
      label: Feature Description
      description: Describe the feature you would like to see added.
    validations:
      required: true

